name: DFT Build

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Update Version
      shell: bash
      id: set-version
      run: echo "{verison}={$(node ./.github/workflows/set-version.js ${{ github.ref }})}" >> "$GITHUB_OUTPUT"
    - run: zip -r ./dft.zip module.json lang/ scripts/ images/ fonts/ scripts/ styles/
    - name: Create Release
      id: create_versioned_release
      uses: ncipollo/release-action@v1
      env:
        VERSION: ${{ steps.set-version.outputs.version }}
      with:
        allowUpdates: true
        name: Release ${{ env.VERSION }}
        draft: false
        prerelease: false
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: './module.json,./dft.zip'